services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    env_file: ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - webnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  alertsys:
    build: ./alertsys
    env_file: ./alertsys/.env
    depends_on: 
      - backend
    networks:
      - webnet

  backend:
    build: ./web_backend
    env_file: ./web_backend/.env.prod
    depends_on: 
      - postgres
    networks:
      - webnet

volumes:
  postgres_data:
    driver: local

networks:
  webnet:
    driver: bridge
