"""add created_at alert

Revision ID: 09e7ce4dfd5f
Revises: fe6e31456864
Create Date: 2025-12-08 20:05:43.536349

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "09e7ce4dfd5f"
down_revision: Union[str, Sequence[str], None] = "fe6e31456864"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "grb_alerts",
        sa.Column(
            "created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("grb_alerts", "created_at")
    # ### end Alembic commands ###
