"""remove relation between event position and observation

Revision ID: 17a237bffe60
Revises: 87c3f6f5420e
Create Date: 2025-11-23 15:04:10.196595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a237bffe60'
down_revision: Union[str, Sequence[str], None] = '87c3f6f5420e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('observations_grb_position_id_fkey'), 'observations', type_='foreignkey')
    op.drop_column('observations', 'grb_position_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('grb_position_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('observations_grb_position_id_fkey'), 'observations', 'grb_positions', ['grb_position_id'], ['id'])
    # ### end Alembic commands ###
