"""add observation image table

Revision ID: 6701deceed54
Revises: 17a237bffe60
Create Date: 2025-11-23 15:25:24.850654

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "6701deceed54"
down_revision: Union[str, Sequence[str], None] = "17a237bffe60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "observation_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("observation_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["observations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("observation_images")
    # ### end Alembic commands ###
