"""create table event alert

Revision ID: 6f7dbd2178cc
Revises: effe51643230
Create Date: 2025-11-20 20:12:42.360934

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "6f7dbd2178cc"
down_revision: Union[str, Sequence[str], None] = "effe51643230"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grb_alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("notice_date", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("notice_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("record_num", sa.Integer(), nullable=False),
        sa.Column("trigger_num", sa.Integer(), nullable=False),
        sa.Column("grb_date", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("grb_time", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("trigger_signif", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("trigger_dur", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("e_range", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("algorithm", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("detectors", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("lc_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("comments", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("grb_alerts")
    # ### end Alembic commands ###
