"""add relation between grb_positions and observations

Revision ID: 87c3f6f5420e
Revises: 9728c918b09e
Create Date: 2025-11-22 16:18:03.377428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '87c3f6f5420e'
down_revision: Union[str, Sequence[str], None] = '9728c918b09e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('grb_position_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'observations', 'grb_positions', ['grb_position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'observations', type_='foreignkey')
    op.drop_column('observations', 'grb_position_id')
    # ### end Alembic commands ###
