"""add relationship one to many event observations

Revision ID: 9582a0754f6a
Revises: b19e0312f233
Create Date: 2025-11-20 21:35:33.230386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9582a0754f6a'
down_revision: Union[str, Sequence[str], None] = 'b19e0312f233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observations', sa.Column('alert_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'observations', 'grb_alerts', ['alert_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'observations', type_='foreignkey')
    op.drop_column('observations', 'alert_id')
    # ### end Alembic commands ###
