"""add table grb_positions

Revision ID: 9728c918b09e
Revises: a8216735fcf4
Create Date: 2025-11-22 16:16:29.057596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9728c918b09e'
down_revision: Union[str, Sequence[str], None] = 'a8216735fcf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grb_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notice_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notice_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('record_num', sa.Integer(), nullable=False),
    sa.Column('trigger_num', sa.Integer(), nullable=False),
    sa.Column('grb_ra', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grb_dec', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grb_error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grb_inten', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_signif', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('integ_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grb_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grb_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grb_phi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('grb_theta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data_time_scale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hard_ratio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('loc_algorithm', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('most_likely', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('second_most_likely', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('detectors', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sun_dist', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('moon_postn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('moon_dist', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('moon_illum', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gal_coords', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ecl_coords', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comments', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grb_positions')
    # ### end Alembic commands ###
