"""add confirmation email

Revision ID: a8216735fcf4
Revises: 9582a0754f6a
Create Date: 2025-11-21 21:20:33.656502

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a8216735fcf4"
down_revision: Union[str, Sequence[str], None] = "9582a0754f6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "email_confirmed", sa.Boolean(), nullable=False, server_default="false"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_confirmed")
    # ### end Alembic commands ###
