"""create table observations

Revision ID: b19e0312f233
Revises: 6f7dbd2178cc
Create Date: 2025-11-20 21:23:00.135456

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "b19e0312f233"
down_revision: Union[str, Sequence[str], None] = "6f7dbd2178cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "observations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("coordinates", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "celestial_reference", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("equinox", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("epoch", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("wave_length", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("instrument", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("magnitude", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("observed_time", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("observations")
    # ### end Alembic commands ###
