"""add receive notification to user

Revision ID: b64017eb47e8
Revises: c297be201d37
Create Date: 2025-11-25 16:38:38.670606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b64017eb47e8'
down_revision: Union[str, Sequence[str], None] = 'c297be201d37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('observations', 'coordinate_system',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('icrs_j2000', 'fk5_j2000', 'b1950', 'galactic', 'current_equinox', name='coordinatesystem'),
               existing_nullable=False,
               existing_server_default=sa.text("'ICRS/J2000'::character varying"))
    op.add_column('users', sa.Column('receive_notification', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'receive_notification')
    op.alter_column('observations', 'coordinate_system',
               existing_type=sa.Enum('icrs_j2000', 'fk5_j2000', 'b1950', 'galactic', 'current_equinox', name='coordinatesystem'),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               existing_server_default=sa.text("'ICRS/J2000'::character varying"))
    # ### end Alembic commands ###
