"""removes too fields in observation table

Revision ID: c297be201d37
Revises: 8a1474297374
Create Date: 2025-11-24 08:57:13.734400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c297be201d37'
down_revision: Union[str, Sequence[str], None] = '8a1474297374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the coordinate_system enum type
    coordinate_system_enum = sa.Enum(
        'icrs_j2000', 'fk5_j2000', 'b1950', 'galactic', 'current_equinox',
        name='coordinatesystem'
    )
    coordinate_system_enum.create(op.get_bind(), checkfirst=True)

    # Add the coordinate_system column with the enum type
    op.add_column('observations', sa.Column('coordinate_system', coordinate_system_enum, nullable=False, server_default='icrs_j2000'))

    op.drop_column('observations', 'celestial_reference')
    op.drop_column('observations', 'magnitude')
    op.drop_column('observations', 'equinox')
    op.drop_column('observations', 'epoch')
    op.drop_column('observations', 'wave_length')
    op.alter_column('users', 'email_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email_confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('observations', sa.Column('wave_length', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('observations', sa.Column('epoch', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('observations', sa.Column('equinox', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('observations', sa.Column('magnitude', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('observations', sa.Column('celestial_reference', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('observations', 'coordinate_system')

    # Drop the coordinate_system enum type
    coordinate_system_enum = sa.Enum(name='coordinatesystem')
    coordinate_system_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
