"""alter table grb_alert with null true

Revision ID: fe6e31456864
Revises: b64017eb47e8
Create Date: 2025-11-30 14:46:56.714265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe6e31456864'
down_revision: Union[str, Sequence[str], None] = 'b64017eb47e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grb_alerts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('grb_alerts', 'notice_date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('grb_alerts', 'notice_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('grb_alerts', 'record_num',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('grb_alerts', 'trigger_num',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('grb_alerts', 'grb_date',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('grb_alerts', 'grb_time',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('grb_alerts', 'trigger_signif',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('grb_alerts', 'trigger_dur',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('grb_alerts', 'e_range',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('grb_alerts', 'algorithm',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('grb_alerts', 'detectors',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('grb_alerts', 'lc_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('grb_alerts', 'comments',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grb_alerts', 'comments',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('grb_alerts', 'lc_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('grb_alerts', 'detectors',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('grb_alerts', 'algorithm',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('grb_alerts', 'e_range',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('grb_alerts', 'trigger_dur',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('grb_alerts', 'trigger_signif',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('grb_alerts', 'grb_time',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('grb_alerts', 'grb_date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('grb_alerts', 'trigger_num',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('grb_alerts', 'record_num',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('grb_alerts', 'notice_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('grb_alerts', 'notice_date',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('grb_alerts', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
