setup:
    uv sync
    uv run db.py
    uv run alembic upgrade head
    mkdir static
    mkdir static/dev

db-build:
    uv run db.py
    uv run python3 -m alembic upgrade head
    uv run python -m seed.seed

seed:
    uv run seed/seed.py
